# Generated by Django 3.2.6 on 2021-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolutions', models.IntegerField(choices=[(72, '72 dpi'), (144, '144 dpi'), (300, '300 dpi')], default=300)),
                ('price_factor', models.IntegerField(default=1)),
            ],
        ),
    ]
