# Generated by Django 3.2.6 on 2021-08-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resolutions',
            new_name='Resolution',
        ),
        migrations.RenameField(
            model_name='resolution',
            old_name='resolutions',
            new_name='resolution',
        ),
    ]
