# Generated by Django 3.2.6 on 2021-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_auto_20210820_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='price_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='resolution',
            field=models.IntegerField(choices=[(72, '72 dpi'), (144, '144 dpi'), (300, '300 dpi')], default=300, unique=True),
        ),
    ]
