# Generated by Django 3.2.6 on 2021-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20210820_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('210 x 297 mm', 'A4'), ('148 x 210 mm', 'A5'), ('105 x 148 mm', 'A6')], default='105 x 148 mm', max_length=12, unique=True)),
                ('price_factor', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
            ],
        ),
    ]
