# Generated by Django 3.2.6 on 2021-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='resolution',
            field=models.CharField(choices=[('72 dpi', 'Low'), ('144 dpi', 'Medium'), ('300 dpi', 'High')], default='72 dpi', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('A4 210 x 297 mm', 'A4'), ('A5 148 x 210 mm', 'A5'), ('A6 105 x 148 mm', 'A6'), ('A7 74 x 105 mm', 'A7')], default='A7 74 x 105 mm', max_length=15, unique=True),
        ),
    ]
