# Generated by Django 3.2.6 on 2021-09-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('commissions', '0006_auto_20210820_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('number_characters', models.SmallIntegerField(default=0)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resolution_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.resolution')),
                ('size_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.size')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.userprofile')),
            ],
        ),
    ]
