# Generated by Django 3.2.6 on 2021-09-04 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('commissions', '0008_auto_20210902_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='number_characters',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6, message='Please enter a number below 6'), django.core.validators.MinValueValidator(0, message='Please enter a number above 0')]),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='profiles.userprofile'),
        ),
        migrations.CreateModel(
            name='WIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_comment', models.TextField()),
                ('wip_illustration', models.ImageField(blank=True, null=True, upload_to='')),
                ('commission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wip', to='commissions.commission')),
            ],
        ),
    ]
