# Generated by Django 3.2.6 on 2021-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='client_review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wip',
            name='client_comment',
            field=models.TextField(blank=True),
        ),
    ]
